apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dag.fullname" . }}-migrate
  labels: {{- include "dag.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels: {{- include "dag.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dag.serviceAccountName" . }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["node", "dist/bootstrap.js", "migration:run"]
          envFrom:
            - configMapRef:
                name: {{ include "dag.fullname" . }}
            - secretRef:
                name: {{ include "dag.fullname" . }}
  backoffLimit: 1
