apiVersion: v1
kind: Secret
metadata:
  name: { { include "dag.fullname" . } }
  labels: { { - include "dag.labels" . | nindent 4 } }
type: Opaque
data:
  PG_PASSWORD_SECRET: { { .Values.postgres.password | b64enc | quote } }
  CRYPTO_SECRET: { { .Values.config.cryptoSecret | b64enc | quote } }
