apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dag.fullname" . }}
  labels: {{- include "dag.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
type: Opaque
data:
  PG_PASSWORD_SECRET: {{ .Values.postgres.password | b64enc | quote }}
  CRYPTO_SECRET: {{ .Values.config.cryptoSecret | b64enc | quote }}
